platform :ios, '13.5.0'
use_frameworks!
inhibit_all_warnings!

# Pods for DiscordLogin
def install_pods
  pod 'Alamofire'
  pod 'RealmSwift'
end

target 'DiscordLogin' do
  install_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end

  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
